language: node_js
before_script:
     - "npm install -g se-interpreter"
script:
     - "se-interpreter Interpreter_config.json"

sauce_connect:
    username: "w2gi"
    secure: "202ec8fe-2b54-44eb-a1c4-bf7fb1be2052"
